In [2]:
import numpy as np

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [4]:
mean_a = a.mean(axis=0)
print(mean_a)

[2.  8.4]


In [5]:
a_centered = a - mean_a
print (a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [6]:
x = a_centered[:, 0]
y = a_centered[:, 1]
a_centered_sp = np.dot(x, y)
a_centered_sp


8.0

In [7]:
N = a.shape[0]
N

5

In [8]:
value = a_centered_sp/(N - 1)
value

2.0

In [9]:
np.cov(a, rowvar = False)

array([[1. , 2. ],
       [2. , 4.3]])